version: '2.4'
services:
  contacts-api:
    ports:
      - 3332:3331
    cpu_count: 2
    cpus: '0.25'
    mem_limit: 2048MB
    container_name: 'contacts-api-prod'

  # mysql-contacts:
  #   image: 'mysql:latest'
  #   restart: 'always'
  #   expose:
  #     - '3302'
  #   ports:
  #     - '3302:3306'
  #   cpu_count: 2
  #   cpus: '0.25'
  #   mem_limit: 1024M
  #   container_name: 'contacts-mysql-prod'
  #   environment:
  #       MYSQL_ROOT_PASSWORD: 'Zj@z#6*l39HR'
  #       MYSQL_DATABASE: 'core'
  #       MYSQL_USER: 'admin'
  #       MYSQL_PASSWORD: 'G9g#x#p0nrrF'
    